import streamlit as st
import pandas as pd
import os
import glob
import streamlit.components.v1 as components
import main  # Your scheduling logic

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Uni-Scheduler Pro",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- ADVANCED UI STYLING (Modern & Readable) ---
st.markdown("""
<style>
    /* Import modern font */
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');

    html, body, [class*="css"] {
        font-family: 'Inter', sans-serif;
    }

    .main-header {
        font-size: 2.8rem; 
        color: #0F172A; 
        font-weight: 800;
        margin-bottom: 0px;
    }
    
    .sub-header {
        font-size: 1.2rem; 
        color: #64748B;
        margin-bottom: 2rem;
    }

    /* Professional Metric Cards */
    .card {
        background-color: #ffffff;
        padding: 24px;
        border-radius: 16px;
        border: 1px solid #E2E8F0;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
        transition: transform 0.2s;
    }
    .card:hover {
        transform: translateY(-5px);
        border-color: #3B82F6;
    }
    .card-label { color: #64748B; font-size: 0.9rem; font-weight: 600; text-transform: uppercase; }
    .card-value { font-size: 2.2rem; font-weight: 800; color: #1E293B; }

    /* Buttons */
    .stButton>button {
        border-radius: 10px;
        font-weight: 600;
        height: 3rem;
    }
</style>
""", unsafe_allow_html=True)

# --- TIMETABLE CSS INJECTION ---
# This styles the HTML tables generated by main.py
TIMETABLE_STYLE = """
<style>
    table {
        width: 100%;
        border-collapse: separate;
        border-spacing: 0;
        margin: 20px 0;
        font-family: 'Inter', sans-serif;
        border: 1px solid #E2E8F0;
        border-radius: 12px;
        overflow: hidden;
    }
    th {
        background-color: #F8FAFC;
        color: #475569;
        font-weight: 700;
        padding: 18px;
        text-align: center;
        border-bottom: 2px solid #E2E8F0;
    }
    td {
        padding: 20px;
        text-align: center;
        border-bottom: 1px solid #F1F5F9;
        color: #1E293B;
        font-size: 0.95rem;
        line-height: 1.5;
        background-color: #ffffff;
        min-width: 120px;
    }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background-color: #F1F5F9; }
    
    /* Highlight cell content */
    .subject { font-weight: 700; color: #2563EB; display: block; }
    .teacher { font-size: 0.8rem; color: #64748B; }
    .room { font-size: 0.8rem; font-weight: 600; color: #059669; background: #ECFDF5; padding: 2px 6px; border-radius: 4px; }
</style>
"""

# --- HELPER FUNCTIONS ---
def load_csv(filename):
    path = os.path.join("data", filename)
    if os.path.exists(path): return pd.read_csv(path)
    return pd.DataFrame()

def save_csv(df, filename):
    path = os.path.join("data", filename)
    df.to_csv(path, index=False)

def get_styled_html(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        html = f.read()
    # Inject our spacing and font style into the HTML
    return TIMETABLE_STYLE + html

# --- SIDEBAR ---
with st.sidebar:
    st.markdown("# 🎓 Uni-Scheduler")
    st.divider()
    menu = st.radio("Navigation", ["📊 Dashboard", "📝 Manage Data", "⚙️ Generator", "📅 View Schedules"])
    st.divider()
    st.info("**Tip:** Set 'Teacher Unavailability' before running the solver for better results.")

# --- DASHBOARD ---
if menu == "📊 Dashboard":
    st.markdown('<p class="main-header">University Dashboard</p>', unsafe_allow_html=True)
    st.markdown('<p class="sub-header">System overview and resource counts</p>', unsafe_allow_html=True)
    
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.markdown(f'<div class="card"><div class="card-label">Teachers</div><div class="card-value">{len(load_csv("teachers.csv"))}</div></div>', unsafe_allow_html=True)
    with col2:
        st.markdown(f'<div class="card"><div class="card-label">Classes</div><div class="card-value">{len(load_csv("classes.csv"))}</div></div>', unsafe_allow_html=True)
    with col3:
        st.markdown(f'<div class="card"><div class="card-label">Rooms</div><div class="card-value">{len(load_csv("rooms.csv"))}</div></div>', unsafe_allow_html=True)
    with col4:
        st.markdown(f'<div class="card"><div class="card-label">Courses</div><div class="card-value">{len(load_csv("curriculum.csv"))}</div></div>', unsafe_allow_html=True)

    st.divider()
    st.subheader("🚀 Quick Actions")
    c1, c2 = st.columns(2)
    with c1:
        if st.button("Open Generator", use_container_width=True):
            st.warning("Please select 'Generator' from the sidebar.")
    with c2:
        st.info("💡 Generate schedules after any change in Data Management.")

# --- MANAGE DATA ---
elif menu == "📝 Manage Data":
    st.markdown('<p class="main-header">Management Center</p>', unsafe_allow_html=True)
    tabs = st.tabs(["👥 Resources", "📖 Academic", "⚠️ Constraints"])
    
    with tabs[0]:
        c1, c2 = st.columns(2)
        for i, file in enumerate(["teachers.csv", "rooms.csv"]):
            with [c1, c2][i]:
                st.subheader(file.capitalize().replace(".csv", ""))
                df = load_csv(file)
                new_df = st.data_editor(df, num_rows="dynamic", key=file, use_container_width=True)
                if st.button(f"Save {file}"):
                    save_csv(new_df, file)
                    st.success("File Updated!")

    with tabs[1]:
        c1, c2 = st.columns(2)
        for i, file in enumerate(["classes.csv", "subjects.csv"]):
            with [c1, c2][i]:
                st.subheader(file.capitalize().replace(".csv", ""))
                df = load_csv(file)
                new_df = st.data_editor(df, num_rows="dynamic", key=file, use_container_width=True)
                if st.button(f"Save {file}"):
                    save_csv(new_df, file)
                    st.success("File Updated!")
        st.divider()
        st.subheader("Curriculum (Course Assignments)")
        df = load_csv("curriculum.csv")
        new_df = st.data_editor(df, num_rows="dynamic", key="curr", use_container_width=True)
        if st.button("Save Curriculum"):
            save_csv(new_df, "curriculum.csv")

    with tabs[2]:
        st.subheader("Teacher Unavailability & Preferences")
        for file in ["teacher_unavailability.csv", "teacher_preferences.csv"]:
            df = load_csv(file)
            new_df = st.data_editor(df, num_rows="dynamic", key=file, use_container_width=True)
            if st.button(f"Update {file}"):
                save_csv(new_df, file)
                st.success("Constraints Saved!")

# --- GENERATOR ---
elif menu == "⚙️ Generator":
    st.markdown('<p class="main-header">Schedule Generator</p>', unsafe_allow_html=True)
    st.info("The AI solver will find the best arrangement based on your constraints. This usually takes 5-30 seconds.")
    
    if st.button("🚀 Run AI Solver", type="primary", use_container_width=True):
        with st.spinner("AI is thinking... optimizing slots and room usage..."):
            result = main.run()
            if "SUCCESS" in result['status']:
                st.success("Schedule Generated Successfully!")
                st.balloons()
            else:
                st.error(result['status'])

# --- VIEW SCHEDULES ---
elif menu == "📅 View Schedules":
    st.markdown('<p class="main-header">Final Timetables</p>', unsafe_allow_html=True)
    
    output_dir = "output"
    if os.path.exists(output_dir):
        files = [f for f in os.listdir(output_dir) if f.endswith(".html")]
        
        col1, col2 = st.columns([1, 3])
        with col1:
            selected = st.selectbox("Choose Schedule", files)
            st.divider()
            st.markdown("### 📥 Export")
            st.caption("Download the HTML file to print or share.")
        
        with col2:
            if selected:
                styled_content = get_styled_html(os.path.join(output_dir, selected))
                components.html(styled_content, height=800, scrolling=True)
                
                with col1:
                    st.download_button("Download HTML", styled_content, file_name=selected, mime="text/html", use_container_width=True)
    else:
        st.warning("No output folder found. Please run the generator.")
